/// Flutter icons Zephyrnaut
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Zephyrnaut
///      fonts:
///       - asset: fonts/Zephyrnaut.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Zephyrnaut {
  Zephyrnaut._();

  static const _kFontFam = 'Zephyrnaut';
  static const _kFontPkg = null;

  static const IconData darkMark = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moneyMark = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signOutMark = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData questionMark = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menuButton = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settingButton = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profileButton = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeButton = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData infoMark = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData historyButton = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qrMark = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moneyWithdrawMark = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boxMark = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cardMark = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
