/// Flutter icons PackMe
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PackMe
///      fonts:
///       - asset: fonts/PackMe.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PackMe {
  PackMe._();

  static const _kFontFam = 'PackMe';
  static const String? _kFontPkg = null;

  static const IconData withdraw = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maps = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skip = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
